-- this table lands an extract from SQL server
-- similar to imports/physical/sqlserver/columns.sql
CREATE TABLE landing_oh_columns(
  "index" INT,
  TABLE_SCHEMA TEXT,
  TABLE_NAME TEXT,
  COLUMN_NAME TEXT,
  ORDINAL_POSITION INT,
  COLUMN_DEFAULT REAL,
  IS_NULLABLE TEXT,
  DATA_TYPE TEXT,
  CHARACTER_MAXIMUM_LENGTH REAL,
  CHARACTER_OCTET_LENGTH REAL,
  NUMERIC_PRECISION REAL,
  NUMERIC_PRECISION_RADIX REAL,
  NUMERIC_SCALE REAL,
  DATETIME_PRECISION REAL,
  CHARACTER_SET_CATALOG REAL,
  CHARACTER_SET_SCHEMA REAL,
  CHARACTER_SET_NAME TEXT,
  COLLATION_CATALOG REAL,
  COLLATION_SCHEMA REAL,
  COLLATION_NAME TEXT,
  DOMAIN_CATALOG REAL,
  DOMAIN_SCHEMA REAL,
  DOMAIN_NAME REAL
);