CREATE TABLE "stg_Py_SynLinkJSONToPhysicalAttribute" (
  "entity_name" TEXT,
  "name" TEXT,
  "dataType" TEXT,
  "maxLength" INTEGER,
  "precision" TEXT,
  "scale" TEXT,
  "RecordSource" TEXT,
  "LoadDate" TIMESTAMP,
  "ModelKeyPhrase" TEXT,
  "SERVER_NAME" TEXT,
  "DATABASE_NAME" TEXT,
  "SCHEMA_NAME" TEXT,
  "PhysicalStructureKeyPhrase" TEXT,
  "PhysicalAttributeKeyPhrase" TEXT,
  "PhysicalStructurePhysicalAttributeKeyPhrase" TEXT,
  "PhysicalStructureHashKey" TEXT,
  "PhysicalAttributeHashKey" TEXT,
  "PhysicalStructurePhysicalAttributeHashKey" TEXT,
  "HashDiff" TEXT
)