CREATE TABLE "stg_Py_SynLinkJSONToPhysicalStructure" (
  "name" TEXT,
  "description" TEXT,
  "RecordSource" TEXT,
  "LoadDate" TIMESTAMP,
  "ModelKeyPhrase" TEXT,
  "SystemKeyPhrase" TEXT,
  "SERVER_NAME" TEXT,
  "DATABASE_NAME" TEXT,
  "SCHEMA_NAME" TEXT,
  "PhysicalStructureKeyPhrase" TEXT,
  "ModelPhysicalStructureKeyPhrase" TEXT,
  "SystemPhysicalStructureKeyPhrase" TEXT,
  "ModelHashKey" TEXT,
  "SystemHashKey" TEXT,
  "PhysicalStructureHashKey" TEXT,
  "ModelPhysicalStructureHashKey" TEXT,
  "SystemPhysicalStructureHashKey" TEXT,
  "HashDiff" TEXT
)