CREATE TABLE "stg_Py_ForeignKeyCsvToPhysicalForeignKey" (
"SERVER_NAME_CHILD" TEXT,
  "DATABASE_NAME_CHILD" TEXT,
  "SCHEMA_NAME_CHILD" TEXT,
  "TABLE_NAME_CHILD" TEXT,
  "COLUMN_NAME_CHILD" TEXT,
  "SERVER_NAME_PARENT" TEXT,
  "DATABASE_NAME_PARENT" TEXT,
  "SCHEMA_NAME_PARENT" TEXT,
  "TABLE_NAME_PARENT" TEXT,
  "COLUMN_NAME_PARENT" TEXT,
  "ORDINAL_POSITION" INTEGER,
  "CONSTRAINT_NAME" TEXT,
  "CONSTRAINT_ENFORCEMENT" TEXT,
  "RecordSource" TEXT,
  "LoadDate" TIMESTAMP,
  "PhysicalAttribute_childKeyPhrase" TEXT,
  "PhysicalAttribute_parentKeyPhrase" TEXT,
  "PhysicalAttribute_childHashKey" TEXT,
  "PhysicalAttribute_parentHashKey" TEXT,
  "PhysicalForeignKeyHashKey" TEXT,
  "PhysicalForeignKeyPhysicalAttributePhysicalAttributeHashKey" TEXT,
  "HashDiff" TEXT
);