CREATE TABLE "stg_Py_DataverseAnalysisCsvToPhysicalAttribute" (
"PhysicalAttributeHashKey" TEXT,
  "PhysicalAttributeKeyPhrase" TEXT,
  "SERVER_NAME" TEXT,
  "DATABASE_NAME" TEXT,
  "SCHEMA_NAME" TEXT,
  "entity_logical_name" TEXT,
  "Logical Name" TEXT,
  "Schema Name" TEXT,
  "Display Name" TEXT,
  "Attribute Type" TEXT,
  "Custom Attribute" INTEGER,
  "Type" TEXT,
  "Additional data" TEXT,
  "Description" TEXT,
  "Tags" TEXT,
  "RecordSource" TEXT,
  "LoadDate" TIMESTAMP,
  "HashDiff" TEXT
);